const path = require("path");

const express = require("express");

const PORT = process.env.PORT || 3001;

const app = require("./app");

// serve static files generated by the frontend build process
app.use(express.static(path.join(__dirname, "..", "client", "dist")));

/** Generic error handler; anything unhandled goes here. */
app.use(function (err, req, res, next) {
  if (process.env.NODE_ENV !== "test") console.error(err.stack);
  const status = err.status || 500;
  const message = err.message;
  return res.status(status).json({
    error: { message, status },
  });
});

app.listen(PORT, () => {
  console.log(`Example app listening at http://localhost:${PORT}`);
});
