const path = require("path");

const express = require("express");

const PORT = process.env.PORT || 3001;

// const app = express();

const app = require("./app");

// serve static files generated by the frontend build process
app.use(express.static(path.join(__dirname, "..", "client", "dist")));

// parse JSON bodies
app.use(express.json());

////////////////////

// prefix all API endpoints with `/api`
app.get("/api/ping", (req, res) => {
  res.send("Ok");
});

app.post("/api/greet", (req, res) => {
  const { name } = req.body;
  // Users.find(name).then((u) => {
  // res.send(`Hi there, ${u.email}!`);
  res.send(`Hi there, ${name}!`);
  // });
});

/** Handle 404 errors -- this matches everything */
app.use(function (req, res, next) {
  return next(new NotFoundError());
});

/** Generic error handler; anything unhandled goes here. */
app.use(function (err, req, res, next) {
  if (process.env.NODE_ENV !== "test") console.error(err.stack);
  const status = err.status || 500;
  const message = err.message;
  return res.status(status).json({
    error: { message, status },
  });
});

/////////////////////////////

if (process.env.NODE_ENV !== "dev") {
  // Catch-All for any request that doesn't match a route
  // falls back to index.html
  app.get("*", (req, res) => {
    res.sendFile(path.join(__dirname, "..", "client", "dist", "index.html"));
  });
}

app.listen(PORT, () => {
  console.log(`Example app listening at http://localhost:${PORT}`);
});
